DROP DATABASE IF EXISTS comm;
CREATE DATABASE comm;
DROP TABLE IF EXISTS comm.ENERGY_RECORD;
CREATE TABLE comm.ENERGY_RECORD (
  ID                        INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  BUILDING_NO               INT              NOT NULL,
  FLOOR_NO                  INT              NOT NULL,
  ROOM_NO                   INT              NOT NULL,
  CURRENT_WATER_VALUE       INT              NOT NULL,
  CURRENT_ELECTRICITY_VALUE FLOAT            NOT NULL,
  CREATED_DATE              DATETIME         NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE =InnoDb
  CHARSET =UTF8;