spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      idle-timeout: 1800
  mail:
    host: smtp.126.com
    username: pumpking2014
    password: software
    address: pumpking2014@126.com
